---
- name: install supervisord via pip
  pip: name=supervisor

- name: create configuration directories
  file: state=directory
        path=/etc/supervisor/conf.d
        owner=root
        group=root
        mode=0644
        recurse=true

- name: copy startup script
  copy: src=supervisor
        dest=/etc/init.d/supervisor
        owner=root
        group=root
        mode=0755

- name: copy configuration script
  copy: src=supervisord.conf
        dest=/etc/supervisor/supervisord.conf
        owner=root
        group=root
        mode=0644

- name: configure supervisord to start at startup
  service: name=supervisor
           enabled=yes
           state=started
